site_name: Max's Knowledge Base
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: amber

  icon:
    logo: material/flask
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
  features:
    - navigation.top
    - navigation.indexes
    - content.code.copy
extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  


  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<max.nuellen@gmail.com>


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


plugins:
  - tags:
      tags_file: tags.md

copyright: Copyright &copy; 2022 - Dr. Max P. Nüllen

#nav:
#  - Tutorials:
#    - Tutorials/index.md
#    - Page 1: Tutorials/1-intro.md
#    - Page n: Tutorials/2-fitting.md